# Generated by Django 5.0.7 on 2024-09-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.SlugField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("content", models.TextField(blank=True, null=True)),
                ("demoLink", models.URLField(blank=True, null=True)),
                ("repoLink", models.URLField(blank=True, null=True)),
                ("thumbnail", models.URLField(blank=True, null=True)),
                ("keyFeatures", models.TextField(blank=True, null=True)),
                ("technologies", models.TextField(blank=True, null=True)),
                ("images", models.JSONField(blank=True, null=True)),
                ("visible", models.BooleanField(default=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        default="Uncategorized", to="projects.category"
                    ),
                ),
            ],
        ),
    ]
