# Generated by Django 5.0.7 on 2024-09-30 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_goal", models.TextField(blank=True, null=True)),
                ("tech_stack", models.TextField(blank=True, null=True)),
                ("features", models.TextField(blank=True, null=True)),
                ("results", models.TextField(blank=True, null=True)),
                ("challenges", models.TextField(blank=True, null=True)),
                ("lessons_learned", models.TextField(blank=True, null=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
