# Generated by Django 5.0.7 on 2024-10-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_projectdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectdetails",
            name="demo_video",
            field=models.URLField(blank=True, null=True),
        ),
    ]
