# Generated by Django 5.1 on 2024-10-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_projectdetails_demo_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="content",
        ),
        migrations.RemoveField(
            model_name="project",
            name="demoLink",
        ),
        migrations.RemoveField(
            model_name="project",
            name="images",
        ),
        migrations.RemoveField(
            model_name="project",
            name="keyFeatures",
        ),
        migrations.RemoveField(
            model_name="project",
            name="repoLink",
        ),
        migrations.RemoveField(
            model_name="project",
            name="technologies",
        ),
        migrations.RemoveField(
            model_name="project",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="projectdetails",
            name="demo_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectdetails",
            name="images",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectdetails",
            name="repo_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectdetails",
            name="thumbnail",
            field=models.URLField(blank=True, null=True),
        ),
    ]
