# Generated by Django 5.1 on 2024-10-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_remove_project_content_remove_project_demolink_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectdetails",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="project",
            name="thumbnail",
            field=models.URLField(blank=True, null=True),
        ),
    ]
