# Generated by Django 5.1 on 2024-10-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_remove_projectdetails_thumbnail_project_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectdetails",
            name="images",
            field=models.TextField(blank=True, null=True),
        ),
    ]
