# Generated by Django 5.0.7 on 2024-08-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("content", models.TextField()),
                ("demoLink", models.URLField()),
                ("repoLink", models.URLField()),
                ("thumbnail", models.URLField()),
                ("keyFeatures", models.JSONField()),
                ("technologies", models.JSONField()),
                ("images", models.JSONField()),
            ],
        ),
    ]
