# Generated by Django 5.0.7 on 2024-08-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.SlugField(
                max_length=100, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
