# Generated by Django 5.0.7 on 2024-09-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_alter_project_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="keyFeatures",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="technologies",
            field=models.TextField(),
        ),
    ]
