# Generated by Django 5.0.7 on 2024-09-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_alter_project_keyfeatures_alter_project_technologies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="demoLink",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="images",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="keyFeatures",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="repoLink",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="technologies",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="thumbnail",
            field=models.URLField(blank=True, null=True),
        ),
    ]
