# Generated by Django 5.0.7 on 2024-09-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0004_alter_project_content_alter_project_demolink_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectDescription",
            fields=[
                (
                    "id",
                    models.SlugField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.TextField(default="Uncategorized"),
        ),
    ]
