# Generated by Django 5.0.7 on 2024-09-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0006_category_remove_project_category_project_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="visibile",
            field=models.BooleanField(default=True),
        ),
    ]
