# Generated by Django 5.0.7 on 2024-09-26 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0007_project_visibile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="visibile",
            new_name="visible",
        ),
    ]
