# Generated by Django 5.0.7 on 2024-09-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aboutme", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnicalSkills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.TextField()),
                ("skill", models.TextField()),
            ],
        ),
    ]
