# Generated by Django 5.0.7 on 2024-09-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aboutme", "0002_technicalskills"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("github", models.URLField()),
                ("website", models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name="professionalexperience",
            old_name="description",
            new_name="responsibilities",
        ),
        migrations.RenameField(
            model_name="professionalexperience",
            old_name="position",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="professionalexperience",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="professionalexperience",
            name="start_date",
        ),
        migrations.AddField(
            model_name="professionalexperience",
            name="duration",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="professionalexperience",
            name="company",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
