# Generated by Django 5.0.7 on 2024-09-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aboutme", "0004_education_resume"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("date", models.TextField(blank=True, null=True)),
                ("issued_by", models.TextField()),
                ("link", models.URLField(blank=True, max_length=500, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="resume",
            name="certifications",
            field=models.ManyToManyField(to="aboutme.certifications"),
        ),
    ]
