# Generated by Django 5.1 on 2024-11-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aboutme", "0005_certifications_resume_certifications"),
    ]

    operations = [
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary_text", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="resume",
            name="summary",
            field=models.ManyToManyField(related_name="resumes", to="aboutme.summary"),
        ),
    ]
