# Generated by Django 5.1 on 2024-11-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aboutme", "0006_summary_resume_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="summary",
            field=models.ManyToManyField(to="aboutme.summary"),
        ),
    ]
