# Generated by Django 5.1 on 2024-11-05 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aboutme", "0007_alter_resume_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="Others",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("details", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="resume",
            name="others",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="aboutme.others",
            ),
        ),
    ]
